# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/two_image_rom/two_image_rom.xci
# IP: The module: 'two_image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/two_image_rom/two_image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_image_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/two_image_rom/two_image_rom.xci
# IP: The module: 'two_image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/two_image_rom/two_image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_image_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
