# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/seven_gcm/seven_gcm.xci
# IP: The module: 'seven_gcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/seven_gcm/seven_gcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seven_gcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/seven_gcm/seven_gcm.xci
# IP: The module: 'seven_gcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rod Bayliss III/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/seven_gcm/seven_gcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seven_gcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
