# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MIT/Class/6.111/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/zero_rcm/zero_rcm.xci
# IP: The module: 'zero_rcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MIT/Class/6.111/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/zero_rcm/zero_rcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zero_rcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/MIT/Class/6.111/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/zero_rcm/zero_rcm.xci
# IP: The module: 'zero_rcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MIT/Class/6.111/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/zero_rcm/zero_rcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zero_rcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
