# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/MIT/Class/6.111/6.111-Minesweeper/minesweeper/minesweeper.srcs/constrs_1/imports/6.111/nexys4_ddr_lab3.xdc

# IP: D:/MIT/Class/6.111/6.111-Minesweeper/minesweeper/minesweeper.srcs/sources_1/ip/clear_fifo/clear_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clear_fifo || ORIG_REF_NAME==clear_fifo} -quiet] -quiet
