# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MIT/Class/6.111/6.111-Minesweeper/minesweeper_audio/minesweeper_audio.srcs/sources_1/ip/one_image_rom/one_image_rom.xci
# IP: The module: 'one_image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MIT/Class/6.111/6.111-Minesweeper/minesweeper_audio/minesweeper_audio.srcs/sources_1/ip/one_image_rom/one_image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_image_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/MIT/Class/6.111/6.111-Minesweeper/minesweeper_audio/minesweeper_audio.srcs/sources_1/ip/one_image_rom/one_image_rom.xci
# IP: The module: 'one_image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MIT/Class/6.111/6.111-Minesweeper/minesweeper_audio/minesweeper_audio.srcs/sources_1/ip/one_image_rom/one_image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_image_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
