# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/6.111/nexys4_ddr_lab3.xdc

# IP: ip/one_bcm/one_bcm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==one_bcm || ORIG_REF_NAME==one_bcm} -quiet] -quiet

# IP: ip/one_rcm/one_rcm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==one_rcm || ORIG_REF_NAME==one_rcm} -quiet] -quiet

# IP: ip/clear_fifo/clear_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clear_fifo || ORIG_REF_NAME==clear_fifo} -quiet] -quiet
